name: CI
on: [push, pull_request]

jobs:
  checks:
    name: Checks
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - run: rustup component add rustfmt clippy
      - run: cargo fmt --all -- --check --files-with-diff
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-targets --all-features
      - run: cargo check
